import type { Metadata } from 'next';
import { Inter, Montserrat, Oswald } from 'next/font/google';
import './globals.css';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Suspense } from 'react';
const inter = Inter({ subsets: ['latin'] });

// Navbar
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'DocsQR',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Suspense>
            <Navbar />
          </Suspense>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}

