import type { Metadata } from 'next';
import { Inter, Montserrat, Oswald } from 'next/font/google';
import './globals.css';
import ConvexClerkProvider from './providers/ConvexClerkProvider';
import { Suspense } from 'react';
import { Toaster } from '@/components/ui/toaster';
import 'simplebar-react/dist/simplebar.min.css';
const inter = Inter({ subsets: ['latin'] });

// Navbar
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'DocsQR',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Suspense>
            <Navbar />
          </Suspense>
          {children}
          <Toaster />
        </body>
      </html>
    </ConvexClerkProvider>
  );
}
